spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  config:
    import:
      - file:/home/ubuntu/app/application-oauth2.yml


logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace


server:
  port: ${SERVER_PORT}
  error:
    include-binding-errors: always
    include-message: always

jwt:
  secret: ${JWT_SECRET}
  token_validity_in_seconds: 38400


file:
  path: ${FILE_PATH}