spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/hangoutwithus;MODE=MariaDB;DATABASE_TO_LOWER=TRUE
    username: sa
    password:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1058432433866-hau4r3l9udgr6gg72lo9tpb6pe47mf82.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/auth/oauth2/code/google
            scope:
              - email
              - profile


logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

jwt:
  secret: aGFuZy1vdXQtd2l0aC1tZS1sb2NhbC1qd3Qtc2VjcmV0Cg==
  token_validity_in_seconds: 38400

file:
  path: /Users/gwonbj/Desktop/test/

server:
  error:
#    include-binding-errors: always
    include-message: always
