spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/hangoutwithus;MODE=MariaDB;DATABASE_TO_LOWER=TRUE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
